#!/usr/bin/python

import rospy
import random
from std_msgs.msg import Int32
from actionlib_msgs.msg import GoalStatusArray
from actionlib_msgs.msg import GoalStatus

class CantStopWontStop:

    first_msg_ = True
    num_goals_ = 14
    last_goal_ = 0
    current_goal_ = ""
    goals_visited_ = 0
    name = "[CantStopWontStop] "

    def __init__(self):
        self.pub = rospy.Publisher('nav_points/goal_number', Int32, queue_size=10)
        rospy.init_node('cant_stop_wont_stop', anonymous=True)

        rospy.Subscriber('/move_base/status', GoalStatusArray, self.callback)

        self.num_goals_= len(rospy.get_param('/nav_points/nav_points'))
        self.wait_for_confirmation_ = rospy.get_param('/nav_points/wait_for_confirmation', False)
        self.pause_time_ = rospy.get_param('/nav_points/pause_time', 5)

        # print configuration
        rospy.loginfo(self.name + "num_goals: " + str(self.num_goals_))
        rospy.loginfo(self.name + "pause_time: " + str(self.pause_time_) + "s")
        rospy.loginfo(self.name + "wait_for_confirmation: " + str(self.wait_for_confirmation_))

    def callback(self, msg):
        if self.first_msg_:
            self.first_msg_ = False
            if len(msg.status_list) > 0:
                self.current_goal_ = msg.status_list[0].goal_id.id

        if len(msg.status_list) == 0:
            return

        oldest_msg = msg.status_list[0]
        if oldest_msg.status == GoalStatus.SUCCEEDED:
            if oldest_msg.goal_id.id != self.current_goal_:
                self.current_goal_ = oldest_msg.goal_id.id

                # ensure no repeats
                new_goal = random.randint(0,self.num_goals_)
                while (new_goal == self.last_goal_):
                    new_goal = random.randint(0,self.num_goals_ - 1)

                rospy.loginfo(self.name + 'Goal reached (' + str(self.goals_visited_) + ' so far)! Setting new goal to ' + str(new_goal))
                self.goals_visited_ += 1

                # wait the specified time
                rospy.sleep(self.pause_time_)

                if (self.wait_for_confirmation_):
                    rospy.logwarn(self.name + "Press enter to set next goal!\n")
                    raw_input()

                self.pub.publish(new_goal)

                self.last_goal_ = new_goal

if __name__ == '__main__':
    csws = CantStopWontStop()
    rospy.spin()
